### ISSUE TITLE
Update the itde_manager's bring_itde_up/take_itde_down functions to let them optionally use an existing container

### ISSUE THREAD

**Issue by ahsimb** [exasol/notebook-connector#131]
The `bring_itde_up(...)` shall have an optional env_info parameter defaulting to None. If it's not None the `api.spawn_test_environment(...)` shall not be called.

An optional parameter to the `take_itde_down(...)` will let it skip the following code

```
    remove_container(conf)
    remove_volume(conf)
    remove_network(conf)
```

This will be called by the DockerDB cleanup externally.

**Comment by redcatbear** [comment]
There is one more test that should be done in a separate. @ahsimb , please create the ticket. Consult with @tkilias , what that mysterious test is.
