### ISSUE TITLE
Use bucketfs-python new SSL verification option

### ISSUE THREAD

**Issue by tkilias** [exasol/notebook-connector#86]
# Background

- Caused by https://github.com/exasol/ai-lab/issues/196
- In https://github.com/exasol/bucketfs-python/releases/tag/0.9.0 we released a new option to configure SSL verification with bucketfs-python

# Acceptance Criteria

- [ ] Use it for transformer-extension deployer wrapper
- [ ] Use it for sagemaker-extension deployer wrapper
- [ ] Use it for open_bucketfs_connection

**Comment by ahsimb** [comment]
The deployer wrappers are passed all ssl parameters already. The problem is that the deployers only use the encryption on/off flag because they call an old bucketfs interface (because it's much faster).
